### ISSUE TITLE
getByMac doesn't seem to work.

### ISSUE THREAD

**Issue by jpambrun** [thib3113/unifi-client#646]
## Prerequisites

Please answer the following questions for yourself before submitting an issue. 

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed

## Current Behavior

``` js
    const client = clients.filter(d=> d.mac === 'ca:f8:f4:50:33:6f')[0];
    console.log(client.mac)                         // prints ca:f8:f4:50:33:6f
    await site.clients.getByMac(client.mac);        // err api.err.UnknownStation
```

 `getByMac` return an error. `getById` works. 

## Expected Behavior

I expect `getByMac` to retrieve clients by mac address.

### Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Library version: unifi-client@0.9.5
* Unifi Controller :UDM SE v3.1.16
* Unifi OS : yes?
* NodeJS version:  v20.2.0
* Operating System: Linux (WSL)

### Failure Logs
Coundn't get that to work, but the essential is that it makes this request :
`GET /proxy/network/api/s/default/stat/sta/ca%3Af8%3Af4%3A50%3A33%3A6f`
and the response is 
``` js
{
        meta: {
          rc: 'error',
          mac: 'ca%3af8%3af4%3a50%3a33%3a6f',
          msg: 'api.err.UnknownStation'
        },
        data: []
      }
```

**Comment by thib3113** [comment]
Hello, thank you for your issue . 

I'm can't try it for the moment (maybe I will have some time at the end of the month) . 

Can you try if it doesn't works too when using `/stat/user/:mac` ?

**Comment by thib3113** [comment]
@jpambrun I fixed in in v0.10.0 . Feel free to test

**Comment by jpambrun** [comment]
Unfortunately is didn't help. I can see the request is now `/proxy/network/api/s/default/stat/sta/ca:f8:f4:50:33:6f`,  but the 400 error is similar.
```
        meta: {
          rc: 'error',
          mac: 'ca:f8:f4:50:33:6f',
          msg: 'api.err.UnknownStation'
        },
```

**Comment by thib3113** [comment]
@jpambrun ok … I don't have the same . 

what is your unifi network version ?

Actually, I tried with : 
```typescript
    const [site] = await controller.getSites();

    const clients = await site.clients.list();
    const client = clients.find((c) => c.mac === '28:6c:07:7a:52:fb');

    if (!client) {
        throw new Error('no client');
    }

    const clientByMac = await site.clients.getByMac(client.mac);
    console.log(clientByMac);
```

And I receive the client . 

Else, I go in unifi web app => enable the legacy interface => go on the clients tab => select a client => I can see a request to https://unifi/proxy/network/api/s/default/stat/user/28:6c:07:7a:52:fb . 

the same for you ? 

if yes, you can try to modify the url in the lib before running your script ? to call `/stat/user/<mac>` insteed of `/stat/sta/<mac>` ( on my two setups the two url do the same things ).
( need to be modified in `node_modules/unifi-client/lib/Clients/Clients.js` line 135 )
![image](https://github.com/thib3113/unifi-client/assets/5489218/5728a18b-f852-4f6c-a273-4af3595fe92b)

**Comment by jpambrun** [comment]
I have UDM SE v3.1.16 with Network 7.5.174.

Using your code snippet the exception is not thrown, but getByMac gets a 400 with api.err.UnknownStation.

In the legacy UI,  I do see `/proxy/network/api/s/default/stat/user/14:c1:4e:14:5c:bd` requests.

And, the proposed code change from `"/stat/sta/"` to `"/stat/user/"` does make it work for me.

**Comment by jpambrun** [comment]
I can also limp by using ```await site.getInstance().get(`/stat/user/${client.mac}`);```

**Comment by thib3113** [comment]
hum ... I can't help if I can't reproduce it ... 

Actually, the only way to get the same error, is to try to get a mac that doesn't exist in my network ...

Can you get the UI to call the url with `ca:f8:f4:50:33:6f` ? or is the error the same with `14:c1:4e:14:5c:bd` ?

**Comment by thib3113** [comment]
@jpambrun any update about this bug ?
